-- Constants.lua

print("dofile Constants.lua")

ITEM_TYPE_OTHER = 0
ITEM_TYPE_SWORD = 1
ITEM_TYPE_SPEAR = 2
ITEM_TYPE_AXE = 3
ITEM_TYPE_BOW = 4
ITEM_TYPE_SHIELD = 5
ITEM_TYPE_CONSUMABLE = 6

FACTION_HOSTILE  = -1;
FACTION_NEUTRAL  =  0;
FACTION_FRIENDLY =  1;
